
sudo: false
language: scala
scala:
- 2.11.8
jdk:
- oraclejdk8
cache:
  directories:
     - $HOME/.m2/repository
     - $HOME/.sbt
     - $HOME/.ivy2
env:
  matrix:
    - TEST_COMMAND="test"
    - TEST_COMMAND="func:test"
script:
  - sbt "$TEST_COMMAND"
  # Trick to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
