kind: "ReplicationController"
apiVersion: "v1"
metadata:
  name: "mongo"
spec:
  replicas: 1
  selector:
    app: "mongo"
  template:
    metadata:
      labels:
        app: "mongo"
    spec:
      containers:
        - name: "mongo"
          image: "mongo:3.3.10"
          ports:
            - containerPort: 27017
