        /obligation:
          get:
            displayName: Retrieve a crystallisation obligation information [test only]
            description: Retrieve a crystallisation obligation information
            (annotations.sandboxData): !include scenarios/crystallisation-obligation-scenarios.md
            is: [headers.acceptHeader, agentSubscription, clientSubscriptionToMTD, testScenarioHeader]
            (annotations.scope): "read:self-assessment"
            securedBy: [ sec.oauth_2_0: { scopes: [ "read:self-assessment" ] } ]
            responses:
              200:
                body:
                  application/json:
                    type: !include schemas/CrystObligation.json
                    examples:
                     example-1:
                      description: Crystallisation obligation open example response
                      value: !include examples/Crystallisation-obligation-open.json
                     example-2:
                      description: Crystallisation obligation fulfilled example response
                      value: !include examples/Crystallisation-obligation-fulfilled.json
              404:
              400:
                body:
                  application/json:
                    type: types.errorResponse
                    examples:
                      invalidNino:
                        description: Invalid NINO
                        value:
                          code: NINO_INVALID
                      invalidTaxYear:
                        description: Invalid taxYear
                        value:
                          code: TAX_YEAR_INVALID